export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST'
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS'
export const WALLET_CREATE_FAIL = 'WALLET_CREATE_FAIL'
export const WALLET_CREATE_RESET = 'WALLET_CREATE_RESET'

export const WALLET_DETAILS_REQUEST = 'WALLET_DETAILS_REQUEST'
export const WALLET_DETAILS_SUCCESS = 'WALLET_DETAILS_SUCCESS'
export const WALLET_DETAILS_FAIL = 'WALLET_DETAILS_FAIL'

export const WALLET_PAY_REQUEST = 'WALLET_PAY_REQUEST'
export const WALLET_PAY_SUCCESS = 'WALLET_PAY_SUCCESS'
export const WALLET_PAY_FAIL = 'WALLET_PAY_FAIL'
export const WALLET_PAY_RESET = 'WALLET_PAY_RESET'