spring:
  application:
    name: product-service
  cloud:
    client:
      hostname: localhost
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:test}:${MONGODB_PWD:password}@${MONGODB_HOST:localhost:27017}/${MONGODB_NAME:ezyShopping}?${MONGODB_OPTIONS:authSource=admin&authMechanism=SCRAM-SHA-256}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    intance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    path: /product-service-swagger.html
  operationsSorter: method