spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:test}:${MONGODB_PWD:password}@${MONGODB_HOST:localhost:27017}/${MONGODB_NAME:ezyShopping}?${MONGODB_OPTIONS:authSource=admin&authMechanism=SCRAM-SHA-256}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /cart-service-swagger.html
  operationsSorter: method